#!/usr/bin/python

import argparse
import re
import subprocess
import sys

def normalize(text):
    def add_newline(s): # TODO report bug
        return re.sub('^([^{]*{)', '\\1\n', s, flags=re.MULTILINE)
    return '%s\n%s\n%s\n' % ('@startdot', add_newline(text), '@enddot')

def write_file(path, data):
    with open(path, 'wb') as output:
        output.write(data)

# immitate 'dot' command (only support few options)
parser = argparse.ArgumentParser()
parser.add_argument('-T', dest='format', default='png')
parser.add_argument('-o', dest='output', required=True)

args = parser.parse_known_args()[0]
proc = subprocess.Popen(['plantuml', '-t' + args.format, '-p'],
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE)
text = normalize(sys.stdin.read())
image = proc.communicate(text)[0]

write_file(args.output, image)
