#!/usr/bin/python
 # -*- coding: utf-8 -*-
 
import argparse
import subprocess
import sys

def read_stdin():
    return "".join(sys.stdin.readlines())

def write_file(path, data):
    with open(path, 'wb') as output:
        output.write(data)

# immitate 'dot' command (only support few options)
parser = argparse.ArgumentParser()
parser.add_argument('-T', dest='format', default='png')
parser.add_argument('-o', dest='output', required=True)

args = parser.parse_known_args()[0]
proc = subprocess.Popen(['plantuml', '-t' + args.format, '-p'],
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE)
text = '%s\n%s\n%s\n' % ('@startdot', read_stdin(), '@enddot')
image = proc.communicate(text.encode('utf-8'))[0]

write_file(args.output, image)
