#!/usr/bin/python

import argparse
import os
import plantuml
import sys

def read_from_stdin():
    return"".join(sys.stdin.readlines())

def to_case_insensitive(strs):
    return map(str.lower, strs)

def write_to_stdout(data):
    try:
        sys.stdout.buffer.write(data)
    except AttributeError:
        sys.stdout.write(data)

# immitate 'plantuml.jar' command (only support few options)
parser = argparse.ArgumentParser()
parser.add_argument('-tpng', dest='format', action='store_const', const='png',
                    default='png')
parser.add_argument('-tsvg', dest='format', action='store_const', const='svg')
parser.add_argument('-ttxt', dest='format', action='store_const', const='txt')
parser.add_argument('-p', '-pipe', action='store_true', required=True)

args = parser.parse_known_args(args=to_case_insensitive(sys.argv))[0]
url = '%s/%s/' % (os.getenv('PLANTUML_SERVER_URL',
                            'http://www.plantuml.com/plantuml'),
                  args.format)
text = read_from_stdin()
data = plantuml.PlantUML(url=url).processes(text)

write_to_stdout(data)
